secretGenerator:
- name: mysql-pass
#- namespace: ingress-controller
  literals:
  - password=d29yZHByZXNz
resources:
  - volumes/mysql-storage.yaml
  - deployment/mysql-deployment.yaml
  - service/mysql-service.yaml
  - volumes/wordpress-storage.yaml
  - deployment/wordpress-deployment.yaml
  - service/wordpress-service.yaml
