apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
  namespace: ingress-controller

spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mysql
  type: LoadBalancer
