apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
  namespace: ingress-controller

spec:
  type: NodePort
  selector:
    app: wordpress
    tier: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007